### PR TITLE
Update boost pin

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Seems reasonable @conda-forge/libdiffpy thoughts?

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by CJ-Wright** [comment]
@jschueller should we have a pinning bot, that just goes around pinning things? (I noticed that you seem to be doing a good job of finding out of date pins)

**Comment by jschueller** [comment]
I think I read conda-forge is already planning that for GSOC projects, ask @conda-forge/core.

**Comment by jakirkham** [comment]
So I don't think a pinning bot will be necessary as `conda-build` 3 takes over that work for us.

**Comment by CJ-Wright** [comment]
Thank you @jschueller

**Pull request merged**
